// libraries
import clsx from 'clsx'
import { useState } from 'react'

// components
import DeleteChart from '@/components/DeleteChart'
import PricePointAnalysis from '@/components/Reports/Charts/PricePointAnalysis'
import PricePointByRetailer from '@/components/Reports/Charts/PricePointByRetailer'
import PriceDistributionByBrand from '@/components/Reports/Charts/PriceDistributionByBrand'
import SkuAnalysis from '@/components/Reports/Charts/SkuAnalysis'
import Colors from '@/components/Reports/Charts/Colors'
import VerticalBars from '@/components/Reports/Charts/VerticalBars'
import HorizontalBars from '@/components/Reports/Charts/HorizontalBars'
import PositiveNegativeBars from '@/components/Reports/Charts/PositiveNegativeBars'

// non-chart components
import ProductPrice from '@/components/Reports/NonCharts/ProductPrice'

// svg
import { Sparkle } from 'lucide-react'

// styles
import styles from './index.module.scss'

// interface
interface ChartBoxProps {
    id: string
    title?: string
    description?: string
    AIGenerated?: boolean
    AIChatChart?: boolean
    boxSize: 'half' | 'full'
    chartType: string
    chartHeight?: number
    showAllNumbers?: boolean
    switchToPercentage?: boolean
    chart: {
        pricePointAnalysis?: Array<{
            id: string
            count: number
        }>
        pricePointByRetailer?: Array<{
            company: string
            min: number
            avg: number
            max: number
        }>
        priceDistributionByBrand?: Array<{
            brand: string
            price: number
        }>
        skuAnalysis?: Array<{
            company: string
            count: number
        }>
        colors?: Array<{
            color: string
            count: number
        }>

        // old charts
        vertical?: Array<{
            label: string
            value: number
        }>
        horizontal?: Array<{
            name: string
            value: number
            color: string
        }>
        positiveNegative?: Array<{
            name: string
            value: number
            color: string
        }>
    }
    reportSummary: {
		retailers?: string[]
		brands?: string[]
		genders?: string[]
		age?: string
		type?: string
		includeImages?: boolean
		timePeriod?: string
		location?: string
		regions?: string[]
		priceRange?: string
	}
}

export default function ChartBox({
    id,
    title,
    description,
    AIGenerated,
    AIChatChart,
    boxSize = 'half',
    chartType,
    chartHeight,
    chart,
    reportSummary,
    showAllNumbers,
    switchToPercentage
}: ChartBoxProps) {
    // State for toggling between numbers and percentages (only for Colors chart)
    const [showAsPercentage, setShowAsPercentage] = useState(false)
    
    // Handle View in % button click
    const handleViewInPercentage = () => {
        setShowAsPercentage(prev => !prev)
    }
    
    return (
        <div
            className={clsx(
                styles.component,
                boxSize === 'full' && styles.full,
                boxSize === 'half' && styles.half
            )}
            data-chart
        >

            {!AIChatChart && (
                <div className={styles.header} data-chart-header>

                    {(title || description) && (
                        <div className={styles.left}>

                            {title && (
                                <h3 className='bold'>
                                    {title}
                                </h3>
                            )}

                            {description && (
                                <p className='text-14'>
                                    {description}
                                </p>
                            )}

                        </div>
                    )}

                    <div className={styles.right}>

                        {AIGenerated && (
                            <div
                                className={styles.AIGenerated}
                                aria-label='This chart was generated by A.I.'
                                data-balloon-pos='up'
                            >

                                <Sparkle />

                                <span className='text-12 semi-bold'>
                                    Gen by A.I.
                                </span>

                            </div>
                        )}

                        {switchToPercentage && (
                            <button
                                className={clsx(
                                    styles.switch, 
                                    'text-14 medium',
                                    showAsPercentage && styles.active
                                )}
                                onClick={handleViewInPercentage}
                            >
                                {showAsPercentage ? 'View as numbers' : 'View in %'}
                            </button>
                        )}

                        <DeleteChart id={id} />

                    </div>

                </div>
            )}

            <div
                className={styles.chart}
                data-chart-type={chartType}
                data-chart-main
            >

                {chart.pricePointAnalysis && (
                    <PricePointAnalysis
                        data={chart.pricePointAnalysis}
                        height={chartHeight}
                        showAllNumbers={showAllNumbers}
                    />
                )}

                {chart.pricePointByRetailer && (
                    <PricePointByRetailer
                        data={chart.pricePointByRetailer}
                        height={chartHeight}
                        reportSummary={{
                            ...reportSummary,
                            regions: reportSummary.regions?.join(',')
                        }}
                    />
                )}

                {chart.skuAnalysis && (
                    <SkuAnalysis
                        data={chart.skuAnalysis}
                        height={chartHeight}
                        reportSummary={{
                            ...reportSummary,
                            regions: reportSummary.regions?.join(',')
                        }}
                        showAllNumbers={showAllNumbers}
                    />
                )}

                {chart.priceDistributionByBrand && (
                    <PriceDistributionByBrand
                        data={chart.priceDistributionByBrand}
                        height={chartHeight}
                        reportSummary={{
                            ...reportSummary,
                            regions: reportSummary.regions?.join(',')
                        }}
                        showAllNumbers={showAllNumbers}
                    />
                )}

                {chart.colors && (
                    <Colors
                        data={chart.colors}
                        height={chartHeight}
                        showAllNumbers={showAllNumbers}
                        showAsPercentage={showAsPercentage}
                    />
                )}

                {/* --- other charts  --- */}

                {chart.vertical && (
                    <VerticalBars
                        data={chart.vertical}
                        //reportSummary={reportSummary}
                        showAllNumbers={showAllNumbers}
                    />
                )}

                {chart.horizontal && (
                    <HorizontalBars
                        data={chart.horizontal}
                        //reportSummary={reportSummary}
                    />
                )}

                {chart.positiveNegative && (
                    <PositiveNegativeBars
                        data={chart.positiveNegative}
                        //reportSummary={reportSummary}
                    />
                )}

            </div>

        </div>
    )
}