export const europeanCountries = [
    { name: 'albania', label: 'Albania' },
    { name: 'andorra', label: 'Andorra' },
    { name: 'austria', label: 'Austria' },
    { name: 'belarus', label: 'Belarus' },
    { name: 'belgium', label: 'Belgium' },
    { name: 'bosnia-and-herzegovina', label: 'Bosnia and Herzegovina' },
    { name: 'bulgaria', label: 'Bulgaria' },
    { name: 'croatia', label: 'Croatia' },
    { name: 'czech-republic', label: 'Czech Republic' },
    { name: 'denmark', label: 'Denmark' },
    { name: 'estonia', label: 'Estonia' },
    { name: 'finland', label: 'Finland' },
    { name: 'france', label: 'France' },
    { name: 'germany', label: 'Germany' },
    { name: 'greece', label: 'Greece' },
    { name: 'hungary', label: 'Hungary' },
    { name: 'iceland', label: 'Iceland' },
    { name: 'ireland', label: 'Ireland' },
    { name: 'italy', label: 'Italy' },
    { name: 'latvia', label: 'Latvia' },
    { name: 'liechtenstein', label: 'Liechtenstein' },
    { name: 'lithuania', label: 'Lithuania' },
    { name: 'luxembourg', label: 'Luxembourg' },
    { name: 'malta', label: 'Malta' },
    { name: 'moldova', label: 'Moldova' },
    { name: 'monaco', label: 'Monaco' },
    { name: 'montenegro', label: 'Montenegro' },
    { name: 'netherlands', label: 'Netherlands' },
    { name: 'north-macedonia', label: 'North Macedonia' },
    { name: 'norway', label: 'Norway' },
    { name: 'poland', label: 'Poland' },
    { name: 'portugal', label: 'Portugal' },
    { name: 'romania', label: 'Romania' },
    { name: 'san-marino', label: 'San Marino' },
    { name: 'serbia', label: 'Serbia' },
    { name: 'slovakia', label: 'Slovakia' },
    { name: 'slovenia', label: 'Slovenia' },
    { name: 'spain', label: 'Spain' },
    { name: 'sweden', label: 'Sweden' },
    { name: 'switzerland', label: 'Switzerland' },
    { name: 'ukraine', label: 'Ukraine' },
    { name: 'vatican-city', label: 'Vatican City' }
] 