export const retailers = [
    "5.11 Tactical",
    "AAFES",
    "Adidas",
    "Adsum",
    "Aime Leon Dore",
    "Amazon (all)",
    "Amazon Best Sellers",
    "Back Country",
    "Bass Pro",
    "Belk",
    "Big 5",
    "BJ's (No Ecomm)",
    "Blains Fleet Farm",
    "Bomgaars",
    "Bootbarn",
    "Burlington (No Ecomm)",
    "Cabela's",
    "Candien Tire",
    "Chaco",
    "Chewy",
    "Columbia",
    "Concepts Shop",
    "Cool J's",
    "Costco",
    "Dicks Sporting Goods",
    "Dillard's",
    "Dr. Jay's",
    "DSW",
    "DTLR",
    "Dunham's",
    "Extra Butter NYC",
    "Famous Footwear",
    "Farm to Feet",
    "Finish Line",
    "Finishline",
    "Fit 3 Run",
    "Five Below",
    "Fleet Feet",
    "Foot Action",
    "Foot Locker",
    "Galls",
    "Golf Galaxy",
    "Goodhood",
    "GovX",
    "H&M",
    "Hibbet",
    "Home Depot",
    "JC Penney",
    "Johnston & Murphy",
    "Journeys",
    "Kamik",
    "Keen",
    "Kith",
    "Kohls",
    "Kroger",
    "L.L. Bean",
    "Lady Foot Locker",
    "Lowes",
    "Macys",
    "Marks Work",
    "Marshalls",
    "Merrell",
    "Mid States",
    "Nex",
    "Nike",
    "Nitty Gritty Store",
    "Nomad Shop",
    "Nordstrom",
    "Nordstrom Rack",
    "North Face",
    "Olukai",
    "Onky NY",
    "Orscheln Farm and Home",
    "Pac Sun",
    "Pajar",
    "Petsmart",
    "PGA Tour Superstore",
    "Primark",
    "Public Lands",
    "Rackroom",
    "REI",
    "Road Runner",
    "Ross Stores (No Ecomm)",
    "RSVP Gallery",
    "Safety First",
    "Saint Alfred Shop",
    "Sams Club",
    "Scheel's",
    "Shoe Carnival",
    "Shoe City",
    "Shoe Dept",
    "Shoe Palace",
    "Shoe Show",
    "Skechers",
    "Snipes USA",
    "Sorel",
    "Sportsman's Warehouse",
    "Stock X",
    "Target",
    "Teva",
    "The Walking Co.",
    "Tik Tok (all)",
    "Tillys",
    "Timberland",
    "TJ Maxx",
    "Tractor Supply",
    "Under Armour",
    "Union Los Angeles",
    "Urban Outfitters",
    "U.S. Patriot",
    "Vans",
    "Walmart",
    "Walmart.com (all)",
    "West Marine",
    "Work N Gear",
    "Zappos",
    "Zara",
    "Zumiez"
]