export const usaStates = [
    { name: 'alabama', label: 'Alabama' },
    { name: 'alaska', label: 'Alaska' },
    { name: 'arizona', label: 'Arizona' },
    { name: 'arkansas', label: 'Arkansas' },
    { name: 'california', label: 'California' },
    { name: 'colorado', label: 'Colorado' },
    { name: 'connecticut', label: 'Connecticut' },
    { name: 'delaware', label: 'Delaware' },
    { name: 'florida', label: 'Florida' },
    { name: 'georgia', label: 'Georgia' },
    { name: 'hawaii', label: 'Hawaii' },
    { name: 'idaho', label: 'Idaho' },
    { name: 'illinois', label: 'Illinois' },
    { name: 'indiana', label: 'Indiana' },
    { name: 'iowa', label: 'Iowa' },
    { name: 'kansas', label: 'Kansas' },
    { name: 'kentucky', label: 'Kentucky' },
    { name: 'louisiana', label: 'Louisiana' },
    { name: 'maine', label: 'Maine' },
    { name: 'maryland', label: 'Maryland' },
    { name: 'massachusetts', label: 'Massachusetts' },
    { name: 'michigan', label: 'Michigan' },
    { name: 'minnesota', label: 'Minnesota' },
    { name: 'mississippi', label: 'Mississippi' },
    { name: 'missouri', label: 'Missouri' },
    { name: 'montana', label: 'Montana' },
    { name: 'nebraska', label: 'Nebraska' },
    { name: 'nevada', label: 'Nevada' },
    { name: 'new-hampshire', label: 'New Hampshire' },
    { name: 'new-jersey', label: 'New Jersey' },
    { name: 'new-mexico', label: 'New Mexico' },
    { name: 'new-york', label: 'New York' },
    { name: 'north-carolina', label: 'North Carolina' },
    { name: 'north-dakota', label: 'North Dakota' },
    { name: 'ohio', label: 'Ohio' },
    { name: 'oklahoma', label: 'Oklahoma' },
    { name: 'oregon', label: 'Oregon' },
    { name: 'pennsylvania', label: 'Pennsylvania' },
    { name: 'rhode-island', label: 'Rhode Island' },
    { name: 'south-carolina', label: 'South Carolina' },
    { name: 'south-dakota', label: 'South Dakota' },
    { name: 'tennessee', label: 'Tennessee' },
    { name: 'texas', label: 'Texas' },
    { name: 'utah', label: 'Utah' },
    { name: 'vermont', label: 'Vermont' },
    { name: 'virginia', label: 'Virginia' },
    { name: 'washington', label: 'Washington' },
    { name: 'west-virginia', label: 'West Virginia' },
    { name: 'wisconsin', label: 'Wisconsin' },
    { name: 'wyoming', label: 'Wyoming' }
] 